---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: react-app-sample
  name: react-app-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app-sample
  template:
    metadata:
      labels:
        app: react-app-sample
    spec:
      containers:
      - image: shuuji3/react-app-sample
        name: react-app-sample
