apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: react-app-sample
build:
  artifacts:
  - image: shuuji3/react-app-sample
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - deploy.yaml
